Repository dhdnjs0702/SORA_X, pull requests merged in 2025-03, with the labels that each got.

#8 ✨ Feature: 랭킹 페이지 기능 구현
  package.json
  src/app/ranking/comment-rank/page.tsx
  src/app/ranking/layout.tsx
  src/app/ranking/page.tsx
  src/components/(ranking)/CommentRank.tsx
  src/components/(ranking)/QuestionRank.tsx
  src/components/(ranking)/RankingHeader.tsx
  src/components/(ranking)/RefreshButton.tsx
  src/constants/ranking/rank.ts
  src/constants/ranking/revalidate-time.ts
  src/utils/ranking/server-action.ts
  tailwind.config.ts
Labels: ✨Feature, 🎨Style

#13 [Feature/nav] 사이드 네비게이션 바 구현 / 라우팅 수정 / UX 개선 완료
  package.json
  public/soraX-logo.png
  src/app/globals.css
  src/app/layout.tsx
  src/components/Header.tsx
  tailwind.config.ts
  yarn.lock
Labels: ✨Feature, 도현

#16 Feature/mainpage
  next.config.mjs
  src/components/mainpage/MainAnswer.tsx
  src/components/mainpage/MainSearchBar.tsx
  src/types/mainTypes.ts
Labels: ✨Feature, 원택

#17 Feature/ranking
  src/app/layout.tsx
  src/app/ranking/layout.tsx
  src/components/(ranking)/CommentRank.tsx
  src/components/(ranking)/QuestionRank.tsx
  src/components/(ranking)/RefreshButton.tsx
  src/constants/ranking/revalidate-time.ts
  src/utils/ranking/server-action.ts
Labels: ✨Feature, 🎨Style, 종연

#18 Feature/mypage
  src/app/mypage/layout.tsx
  src/app/mypage/mycomments/page.tsx
  src/app/mypage/page.tsx
  src/app/supabase/client.ts
  src/components/(mypage)/Myanswercard.tsx
  src/components/(mypage)/Mycommentcard.tsx
  src/types/mypageTypes.ts
Labels: ✨Feature, 🎨Style, 선영

#19 Feature/mainpage
  src/app/api/openai/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/mainpage/MainAnswer.tsx
  src/components/mainpage/MainFileUploader.tsx
  src/components/mainpage/MainSearchBar.tsx
  src/constants/mainpage/cardComment.ts
  src/utils/mainpage/mainSupabase.ts
Labels: 🔨Refactor, 원택

#21 Feature/login,signin
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/(login,signup)/Form.tsx
  src/components/(login,signup)/LoginForm.tsx
  src/components/(login,signup)/SignUpForm.tsx
  src/components/(login,signup)/Sora.tsx
  src/components/(login,signup)/ToggleLogIn.tsx
  src/stores/store.ts
Labels: ✨Feature, 익환

#22 Feature/mypage 시헌님께 데이터 건네주기 📩
  src/app/mypage/mycomments/page.tsx
  src/app/mypage/page.tsx
  src/components/(mypage)/Myanswercard.tsx
  src/components/(mypage)/Mycommentcard.tsx
Labels: ✨Feature, 선영

#25 [Feature/nav] 질문의 광장 페이지 구현 / 소라멤버스 페이지 구현 / sweetalert 파일 생성
  public/face-IU.png
  public/face-doni.png
  public/face-honey.png
  public/face-one.png
  public/face-sun.png
  public/face-tutor.png
  public/face-yeon.png
  src/app/community/page.tsx
  src/app/contact/page.tsx
  src/app/layout.tsx
  src/components/(login,signup)/ToggleLogIn.tsx
  src/components/Header.tsx
  src/types/mainTypes.ts
  src/utils/alert.ts
  tailwind.config.ts
Labels: ✨Feature, 🎨Style, 도현

#26 Feature/mainpage
  src/app/layout.tsx
  src/components/mainpage/MainSearchBar.tsx
  src/constants/mainpage/cardComment.ts
Labels: ✨Feature, 원택

#29 🩹 fix: 로그인 상태일때 로그인페이지로 가는 걸 막는 로직 구현
  src/components/(login,signup)/LoginForm.tsx
Labels: ✨Feature, 익환

#30 Feature/mypage 유저 정보 및 삭제
  src/app/mypage/layout.tsx
  src/app/mypage/mycomments/page.tsx
  src/app/mypage/page.tsx
  src/components/(mypage)/Myanswercard.tsx
  src/components/(mypage)/Mycommentcard.tsx
  src/components/(mypage)/mypageHeader.tsx
  src/types/mypageTypes.ts
Labels: ✨Feature, 선영

#31 Feature/mainpage
  src/components/mainpage/MainSearchBar.tsx
Labels: 🐞BugFix, 원택

#32 Feature/mypage 텐스택
  src/app/mypage/layout.tsx
  src/app/mypage/mycomments/page.tsx
  src/app/mypage/page.tsx
  src/components/(mypage)/Myanswercard.tsx
  src/components/(mypage)/Mycommentcard.tsx
  src/hooks/mypage/useUserData.ts
  src/utils/mypage/mypagedelete.ts
Labels: ✨Feature, 선영

#36 Feature/detail
  src/app/community/page.tsx
  src/app/detail/[id]/page.tsx
  src/components/(detail)/comments/CommentInput.tsx
  src/components/(detail)/comments/CommentList.tsx
  src/utils/detail/addComment.ts
Labels: 🔨Refactor, 시헌

#37 ✨ Feature/ranking 랭킹페이지 css 수정
  src/app/ranking/layout.tsx
  src/components/(ranking)/CommentRank.tsx
  src/components/(ranking)/QuestionRank.tsx
  src/components/(ranking)/RankingHeader.tsx
  src/components/(ranking)/RefreshButton.tsx
Labels: 🎨Style, 종연

#38 Feature/mypage 기타등등
  src/app/mypage/layout.tsx
  src/app/mypage/mycomments/page.tsx
  src/app/mypage/page.tsx
  src/components/(mypage)/Myanswercard.tsx
  src/components/(mypage)/Mycommentcard.tsx
  src/hooks/mypage/useUserData.ts
Labels: ✨Feature, 선영

#40 ✨ feat/ 게시글, 댓글 순서 지정 최근에 쓴게 위쪽으로 오도록록
  src/hooks/mypage/useUserData.ts
Labels: 선영

#41 🩹 fix: sweetalert로 알림창 변경, useEffect 의존성 추가
  src/components/(login,signup)/LoginForm.tsx
Labels: 🔨Refactor, 익환

#46 [Feature/nav] 질문의 광장 페이지 구현 완료
  src/app/community/page.tsx
  src/app/contact/page.tsx
  src/app/layout.tsx
  src/components/(detail)/QuestionDetail.tsx
  src/types/mainTypes.ts
  yarn.lock
Labels: ✨Feature, 🎨Style, 도현

#49 ✨ feat/ 로그인 안 했을 때 마이페이지 안 보이도록.
  src/components/(mypage)/ToggleMypage.tsx
  src/components/Header.tsx
Labels: 선영

#50 [Feature/nav] README 파일 작성
  README.md
Labels: 📄Docs, 도현

#57 [Feature/nav] 멤버 소개 페이지 작업 완료
  src/app/contact/page.tsx
Labels: ✨Feature, 도현

#58 ♻️ 주석 제거
  src/app/api/openai/route.ts
  src/app/layout.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/mycomments/page.tsx
  src/components/(detail)/comments/CommentList.tsx
  src/components/(mypage)/mypageHeader.tsx
  src/components/(ranking)/RankingHeader.tsx
  src/components/Header.tsx
  src/hooks/mypage/useUserData.ts
  src/stores/store.ts
  src/types/commentTypes.ts
  src/types/mainTypes.ts
  src/utils/alert.ts
  src/utils/detail/fetchAnswerById.ts
  src/utils/detail/fetchCommentById.ts
Labels: 선영
